<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <Product>MADE.NET Diagnostics</Product>
    <Description>
      MADE.NET Diagnostics provides helpers to make debugging and logging results in your applications easier.
    </Description>
    <PackageTags>MADE Diagnostics Extensions Logging EventLog Logger Exception Stopwatch</PackageTags>
  </PropertyGroup>

</Project>
