<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <Product>MADE.NET Collections</Product>
    <Description>
      MADE.NET Collections allows you to easily interact with collections, lists, arrays, and dictionaries.
    </Description>
    <PackageTags>MADE Collection List Array Dictionary Queryable Observable Equality Extensions Chunk</PackageTags>
  </PropertyGroup>

</Project>