<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <Product>MADE.NET Networking</Product>
    <Description>
      MADE.NET Networking comes fully loaded with wrappers for easily executing network requests from applications, handling the responses, as well as providing extensions for common URI scenarios.
      A perfect companion to any application handling networking.
    </Description>
    <PackageTags>MADE Networking Extensions Json Stream HttpClient</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MADE.Runtime\MADE.Runtime.csproj" />
    <ProjectReference Include="..\MADE.Threading\MADE.Threading.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='net8.0'">
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.*" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='net10.0'">
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.*" />
  </ItemGroup>

</Project>
