#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MADE.UnitTests.Droid.Resource", IsApplication=true)]

namespace MADE.UnitTests.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MADE.UI.Controls.Resource.Attribute.header = global::MADE.UnitTests.Droid.Resource.Attribute.header;
			global::MADE.UI.Controls.Resource.Attribute.hide_if_empty = global::MADE.UnitTests.Droid.Resource.Attribute.hide_if_empty;
			global::MADE.UI.Controls.Resource.Attribute.text = global::MADE.UnitTests.Droid.Resource.Attribute.text;
			global::MADE.UI.Controls.Resource.Color.accent = global::MADE.UnitTests.Droid.Resource.Color.accent;
			global::MADE.UI.Controls.Resource.Color.colorActivated = global::MADE.UnitTests.Droid.Resource.Color.colorActivated;
			global::MADE.UI.Controls.Resource.Color.colorHighlight = global::MADE.UnitTests.Droid.Resource.Color.colorHighlight;
			global::MADE.UI.Controls.Resource.Color.primary = global::MADE.UnitTests.Droid.Resource.Color.primary;
			global::MADE.UI.Controls.Resource.Color.primaryDark = global::MADE.UnitTests.Droid.Resource.Color.primaryDark;
			global::MADE.UI.Controls.Resource.Color.textPrimary = global::MADE.UnitTests.Droid.Resource.Color.textPrimary;
			global::MADE.UI.Controls.Resource.Id.htb_container = global::MADE.UnitTests.Droid.Resource.Id.htb_container;
			global::MADE.UI.Controls.Resource.Id.htb_header = global::MADE.UnitTests.Droid.Resource.Id.htb_header;
			global::MADE.UI.Controls.Resource.Id.htb_text = global::MADE.UnitTests.Droid.Resource.Id.htb_text;
			global::MADE.UI.Controls.Resource.Layout.HeaderedTextBlock = global::MADE.UnitTests.Droid.Resource.Layout.HeaderedTextBlock;
			global::MADE.UI.Controls.Resource.Style.HeaderedTextBlockHeaderStyle = global::MADE.UnitTests.Droid.Resource.Style.HeaderedTextBlockHeaderStyle;
			global::MADE.UI.Controls.Resource.Style.HeaderedTextBlockTextStyle = global::MADE.UnitTests.Droid.Resource.Style.HeaderedTextBlockTextStyle;
			global::MADE.UI.Controls.Resource.Styleable.HeaderedTextBlock = global::MADE.UnitTests.Droid.Resource.Styleable.HeaderedTextBlock;
			global::MADE.UI.Controls.Resource.Styleable.HeaderedTextBlock_header = global::MADE.UnitTests.Droid.Resource.Styleable.HeaderedTextBlock_header;
			global::MADE.UI.Controls.Resource.Styleable.HeaderedTextBlock_hide_if_empty = global::MADE.UnitTests.Droid.Resource.Styleable.HeaderedTextBlock_hide_if_empty;
			global::MADE.UI.Controls.Resource.Styleable.HeaderedTextBlock_text = global::MADE.UnitTests.Droid.Resource.Styleable.HeaderedTextBlock_text;
			global::MADE.UI.Resource.Color.accent = global::MADE.UnitTests.Droid.Resource.Color.accent;
			global::MADE.UI.Resource.Color.colorActivated = global::MADE.UnitTests.Droid.Resource.Color.colorActivated;
			global::MADE.UI.Resource.Color.colorHighlight = global::MADE.UnitTests.Droid.Resource.Color.colorHighlight;
			global::MADE.UI.Resource.Color.primary = global::MADE.UnitTests.Droid.Resource.Color.primary;
			global::MADE.UI.Resource.Color.primaryDark = global::MADE.UnitTests.Droid.Resource.Color.primaryDark;
			global::MADE.UI.Resource.Color.textPrimary = global::MADE.UnitTests.Droid.Resource.Color.textPrimary;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = global::MADE.UnitTests.Droid.Resource.Id.OptionHostName;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionPort = global::MADE.UnitTests.Droid.Resource.Id.OptionPort;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = global::MADE.UnitTests.Droid.Resource.Id.OptionRemoteServer;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = global::MADE.UnitTests.Droid.Resource.Id.OptionsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = global::MADE.UnitTests.Droid.Resource.Id.ResultFullName;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = global::MADE.UnitTests.Droid.Resource.Id.ResultMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = global::MADE.UnitTests.Droid.Resource.Id.ResultResultState;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultRunSingleMethodTest = global::MADE.UnitTests.Droid.Resource.Id.ResultRunSingleMethodTest;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = global::MADE.UnitTests.Droid.Resource.Id.ResultStackTrace;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = global::MADE.UnitTests.Droid.Resource.Id.ResultsFailed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsId = global::MADE.UnitTests.Droid.Resource.Id.ResultsId;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = global::MADE.UnitTests.Droid.Resource.Id.ResultsIgnored;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = global::MADE.UnitTests.Droid.Resource.Id.ResultsInconclusive;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = global::MADE.UnitTests.Droid.Resource.Id.ResultsMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = global::MADE.UnitTests.Droid.Resource.Id.ResultsPassed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = global::MADE.UnitTests.Droid.Resource.Id.ResultsResult;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = global::MADE.UnitTests.Droid.Resource.Id.RunTestsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = global::MADE.UnitTests.Droid.Resource.Id.TestSuiteListView;
			global::Xamarin.Android.NUnitLite.Resource.Layout.options = global::MADE.UnitTests.Droid.Resource.Layout.options;
			global::Xamarin.Android.NUnitLite.Resource.Layout.results = global::MADE.UnitTests.Droid.Resource.Layout.results;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_result = global::MADE.UnitTests.Droid.Resource.Layout.test_result;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_suite = global::MADE.UnitTests.Droid.Resource.Layout.test_suite;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int header = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int hide_if_empty = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int text = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040004
			public const int accent = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int colorActivated = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int colorHighlight = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int primary = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int primaryDark = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int textPrimary = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070004
			public const int OptionHostName = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int OptionPort = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int OptionRemoteServer = 2131165187;
			
			// aapt resource value: 0x7f070013
			public const int OptionsButton = 2131165203;
			
			// aapt resource value: 0x7f07000e
			public const int ResultFullName = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int ResultMessage = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int ResultResultState = 2131165199;
			
			// aapt resource value: 0x7f07000d
			public const int ResultRunSingleMethodTest = 2131165197;
			
			// aapt resource value: 0x7f070011
			public const int ResultStackTrace = 2131165201;
			
			// aapt resource value: 0x7f070009
			public const int ResultsFailed = 2131165193;
			
			// aapt resource value: 0x7f070006
			public const int ResultsId = 2131165190;
			
			// aapt resource value: 0x7f07000a
			public const int ResultsIgnored = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int ResultsInconclusive = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int ResultsMessage = 2131165196;
			
			// aapt resource value: 0x7f070008
			public const int ResultsPassed = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int ResultsResult = 2131165191;
			
			// aapt resource value: 0x7f070012
			public const int RunTestsButton = 2131165202;
			
			// aapt resource value: 0x7f070014
			public const int TestSuiteListView = 2131165204;
			
			// aapt resource value: 0x7f070000
			public const int htb_container = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int htb_header = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int htb_text = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int HeaderedTextBlock = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int options = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int results = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int test_result = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int test_suite = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int HeaderedTextBlockHeaderStyle = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int HeaderedTextBlockTextStyle = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] HeaderedTextBlock = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int HeaderedTextBlock_header = 0;
			
			// aapt resource value: 2
			public const int HeaderedTextBlock_hide_if_empty = 2;
			
			// aapt resource value: 1
			public const int HeaderedTextBlock_text = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
