name: Bug
description: Log a bug to help us improve
title: "[Bug] "
labels: [bug]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: Please describe below the details of the issue and steps taken to reproduce.
  - type: textarea
    attributes:
      label: What is the expected behavior?
      description: Please describe below what you expected to happen.
  - type: dropdown
    attributes:
      label: Package
      options:
        - "Collections"
        - "Data.Converters"
        - "Data.EFCore"
        - "Data.Security"
        - "Data.Validation"
        - "Data.Validation.FluentValidation"
        - "Diagnostics"
        - "Foundation"
        - "Networking"
        - "Runtime"
        - "Testing"
        - "Threading"
        - "Web"
        - "Web.Mvc"
  - type: textarea
    attributes:
      label: Other information
      description: Please provide any additional information, links, screenshots, or projects with reproduced issues below if applicable
