#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MADE.UI.Resource", IsApplication=false)]

namespace MADE.UI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f020004
			public static int accent = 2130837508;
			
			// aapt resource value: 0x7f020000
			public static int colorActivated = 2130837504;
			
			// aapt resource value: 0x7f020005
			public static int colorHighlight = 2130837509;
			
			// aapt resource value: 0x7f020001
			public static int primary = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int primaryDark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int textPrimary = 2130837507;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
	}
}
#pragma warning restore 1591
