<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MADE.Data.Converters\MADE.Data.Converters.csproj" />
    <ProjectReference Include="..\..\src\MADE.Data.Validation.FluentValidation\MADE.Data.Validation.FluentValidation.csproj" />
    <ProjectReference Include="..\..\src\MADE.Testing\MADE.Testing.csproj" />
  </ItemGroup>

</Project>