#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MADE.UI.Controls.Resource", IsApplication=false)]

namespace MADE.UI.Controls
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int header = 2130771968;
			
			// aapt resource value: 0x7f010002
			public static int hide_if_empty = 2130771970;
			
			// aapt resource value: 0x7f010001
			public static int text = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f030004
			public static int accent = 2130903044;
			
			// aapt resource value: 0x7f030000
			public static int colorActivated = 2130903040;
			
			// aapt resource value: 0x7f030005
			public static int colorHighlight = 2130903045;
			
			// aapt resource value: 0x7f030001
			public static int primary = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int primaryDark = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int textPrimary = 2130903043;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public static int htb_container = 2131034112;
			
			// aapt resource value: 0x7f050001
			public static int htb_header = 2131034113;
			
			// aapt resource value: 0x7f050002
			public static int htb_text = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public static int HeaderedTextBlock = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040001
			public static int HeaderedTextBlockHeaderStyle = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int HeaderedTextBlockTextStyle = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] HeaderedTextBlock = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public static int HeaderedTextBlock_header = 0;
			
			// aapt resource value: 2
			public static int HeaderedTextBlock_hide_if_empty = 2;
			
			// aapt resource value: 1
			public static int HeaderedTextBlock_text = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
