name: Docs

on:
  push:
    branches:
    - main
    paths:
    - src/**
    - docs/**
    - .github/workflows/docs.yml
  pull_request:
    branches:
    - main
    paths:
    - docs/**
    - .github/workflows/docs.yml
  workflow_dispatch:

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: write

jobs:
  generate-docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x

    - name: Setup .NET 10.0
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.3xx

    - name: Install DocFX
      run: dotnet tool install -g docfx

    - name: Restore projects
      run: dotnet restore MADE.NET.sln

    - name: Build DocFX site
      working-directory: docs
      run: docfx docfx.json
      continue-on-error: false

    - name: Publish DocFX site
      if: github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_site
        force_orphan: true
